services:
  minio:
    image: minio/minio:latest
    container_name: minio-s3
    ports:
      - "9000:9000" # Api
      - "9001:9001" # Admin Web Console
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
      MINIO_ACCESS_KEY: "minioadmin"
      MINIO_SECRET_KEY: "minioadmin"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  minio_data: