services:
  ofelia:
    image: mcuadros/ofelia:latest
    depends_on:
      - nginx
      - bullmq
      - agenda
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      ofelia.job-local.my-test-job.schedule: "@every 5s"
      ofelia.job-local.my-test-job.command: "date"

  nginx:
    image: nginx
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.datecron.schedule: "@every 5s"
      ofelia.job-exec.datecron.command: "uname -a"

  agenda:
    build:
      context: ./
      dockerfile: Dockerfile
#    restart: always
#    command: "npx pm2 start build/agenda.js"
    command: "node build/agenda.js"
    depends_on:
      - mongodb
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.agenda-uname-cron.schedule: "@every 5s"
      ofelia.job-exec.agenda-uname-cron.command: "uname -a"

  bullmq:
    build:
      context: ./
      dockerfile: Dockerfile
#    restart: always
#    command: "npx pm2 start build/bullmq.js"
    command: "node build/bullmq.js"
    depends_on:
      - redis
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.bullmq-uname-cron.schedule: "@every 5s"
      ofelia.job-exec.bullmq-uname-cron.command: "uname -a"

  pm2-node-cron:
    build:
      context: ./
      dockerfile: Dockerfile
#    restart: always
    command: "npx pm2 start pm2.ecosystem.config.js"
    depends_on:
      - mongodb
      - redis

  pm2-cron:
    build:
      context: ./
      dockerfile: Dockerfile
#    restart: always
    command: "npx pm2 start build/pm2-buildin-cronjob.js --no-autorestart --instances 1 --cronjob \"*/5 * * * * *\""
    depends_on:
      - mongodb
      - redis

  redis:
    image: "redis:alpine"
#    restart: always
    ports:
      - "6379:6379"

  mongodb:
    image: "mongo:4.4"
#    restart: always
    ports:
      - "27017:27017"
#    volumes:
#      - mongodb_data:/data/db
#
#volumes:
#  mongodb_data:
